CREATE TABLE JOB_History (
	 ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	 Employee_ID INT NOT NULL,
	 Start_Date INT NOT NULL,
	 End_Date INT NOT NULL,
	 JOB_ID VARCHAR(10) NOT NULL,
	 Departement_ID INT
);